//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetisyenApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaTable
    {
        public int Id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string tc { get; set; }
        public Nullable<int> yas { get; set; }
        public Nullable<int> kilo { get; set; }
        public string hastalikTipi { get; set; }
        public string uygulanacakDiyet { get; set; }
        public string doktorAdi { get; set; }
    }
}
